syntax = "proto3";

package otp;

// This is the Go package name
option go_package = "otppb/";

// OTP service
service OtpService {
  rpc hello(HelloRequest) returns (HelloResponse);

  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Verify(VerifyRequest) returns (VerifyResponse);
  rpc Get(GetRequest) returns (GetResponse);
  rpc SendMessage(SendMessageRequest) returns (SendMessageResponse);
  // Email OTP methods
  rpc CreateByEmail(CreateByEmailRequest) returns (CreateByEmailResponse);
  rpc VerifyByEmail(VerifyByEmailRequest) returns (VerifyByEmailResponse);
}

// Hello request and response
message HelloRequest {
  string name = 1;
}

message HelloResponse {
  string message = 1;
}

// Create OTP request and response
message CreateRequest {
  string phone_number = 1;
}

message CreateResponse {
  bool status = 1;
}

// Verify OTP request and response
message VerifyRequest {
  string phone_number = 1;
  string code = 2;
}

message VerifyResponse {
  bool status = 1;
}

// Get OTP request and response
message GetRequest {
  string phone_number = 1;
}

message GetResponse {
  string code = 1;
}

// Send message request and response
message SendMessageRequest {
  string phone_number = 1;
  string message = 2;
}

message SendMessageResponse {
  bool status = 1;
}

// Send email request and response
message SendEmailRequest {
  string to_email = 1;
}

message SendEmailResponse {
  bool status = 1;
}

// Create OTP by email request and response
message CreateByEmailRequest {
  string email = 1;
}

message CreateByEmailResponse {
  bool status = 1;
}

// Verify OTP by email request and response
message VerifyByEmailRequest {
  string email = 1;
  string code = 2;
}

message VerifyByEmailResponse {
  bool status = 1;
}